#!/bin/sh

git --work-tree=/var/www/zug-lol --git-dir=/var/www/zug-lol.git checkout -f
cd /var/www/zug-lol || exit
python3 -m venv venv
venv/bin/pip install wheel
venv/bin/pip install --upgrade -r requirements.txt
venv/bin/pybabel compile -d app/translations
venv/bin/flask db upgrade
sudo systemctl restart zug-lol.service
