"""Revert test migration

Revision ID: 8ffa33cf23ae
Revises: d211c9345492
Create Date: 2022-06-23 15:41:00.429393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffa33cf23ae'
down_revision = 'd211c9345492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_vorteilscard2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_vorteilscard2', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
